name: BoostersX
version: '${project.version}'
main: me.frxq15.boostersx.BoostersX
api-version: '1.18'
author: 'frxq'

commands:
  abooster:
    usage: '/abooster'
    description: 'Booster admin command'
  booster:
    usage: '/booster'
    description: 'Booster command'
